### ISSUE TITLE
Ambiguous import : Status enum defined in both model and storage

### ISSUE THREAD

**Issue by ikerfah** [leam-tech/renovation_core.dart#2]
Hey,
When i tried to use storage controller with uploadFile method and listen to the stream emitted,
i can't use Status enum provided by storage lib because Status is already defined in the model lib.
(Same name but different implementations).
So the problem is :
`error: The name 'Status' is defined in the libraries 'package:lts_renovation_core/src/model/interfaces.dart (via package:lts_renovation_core/model.dart)' and 'package:lts_renovation_core/src/storage/interfaces.dart'. (ambiguous_import at [cookbook_sample_app] lib/core/services/api.dart:186)`

My temporary solution was to use **as** prefix:
`import 'package:lts_renovation_core/src/storage/interfaces.dart' as Storage;`

Using this temporary is not good for dart and the compiler throws lint info as following: 
**info: Don't import implementation files from another package.**
and is why [Don't](https://dart-lang.github.io/linter/lints/implementation_imports.html)

**Comment by nabilshuja** [comment]
@assemmarwan I suppose we can refactor Status enum, due to this.
