### ISSUE TITLE
The app "renovation_core" is not installed in the backend [v13]

### ISSUE THREAD

**Issue by ikerfah** [leam-tech/renovation_core.dart#20]
Hello,
I'm trying to migrate the app API endpoint to new one running on frappe version 13 (current is 12)
i'm getting this error message :
```
The app "renovation_core" is not installed in the backend.
```

I tried also to signup and use SMS OTP verification and i got this error too 
```
Please install it to be able to use the feature(s):

sendOTP
```

Any suggestions ?

**Comment by nabilshuja** [comment]
@ikerfah by any chance did you not update renovation_core to the latest 1.2.2? 

Since the frappe app version naming for v13 includes text within it. Which was unsupported below 1.2.2.
