### ISSUE TITLE
DocPerm not defined

### ISSUE THREAD

**Issue by ikerfah** [leam-tech/renovation_core.dart#6]
Hi all,
I'm trying to use ```getPerm``` method from ```getFrappePermissionController```,
This method has as return type ```RequestResponse<List<DocPerm>>```
I can't import ```DocPerm``` to continue, And the IDE is asking to create the class so i think it's not visible or not exported.
The code i tried to run :
```
RequestResponse<List<DocPerm>> getPermResult = await getFrappePermissionController().getPerm(
  doctype: "Item"
);
```

**Comment by nabilshuja** [comment]
is there any reason why you're not doing `var getPermResult` so that dart infers the type?

it does however seem that perm.dart doesn't seem to export `frappe/interfaces.dart';`
cc @assemmarwan

**Comment by assemmarwan** [comment]
Yeah, it should be exported. Will need to make a PR involving exporting interfaces in general.

**Comment by ikerfah** [comment]
@nabilshuja 
i'm trying to make the type explicit for a documentation purpose :D
